#schrankraum
- topic: home/og/schrank/licht
  physical:
    type: do31
    address: 240
    digout: 7
- topic: home/og/schrank/rollo
  physical:
    type: do31
    address: 241
    shader: 7

#schlafzimmer
- topic: home/og/schlaf/licht
  physical:
    type: do31
    address: 240
    digout: 8
- topic: home/og/schlaf/rollo
  physical:
    type: do31
    address: 241
    shader: 8

#bad
- topic: home/og/bad/spiegel/licht
  physical:
    type: do31
    address: 240
    digout: 10
- topic: home/og/bad/licht
  physical:
    type: do31
    address: 240
    digout: 12

#vorraum og
- topic: home/og/vorraum/licht
  physical:
    type: do31
    address: 240
    digout: 11

#wohn
- topic: home/eg/wohn/licht
  physical:
    type: do31
    address: 240
    digout: 13
- topic: home/eg/wohn/lesen/licht
  physical:
    type: do31
    address: 240
    digout: 14

#vorraum eg
- topic: home/eg/vorraum/licht
  physical:
    type: do31
    address: 240
    digout: 16

#wc eg
- topic: home/eg/wc/licht
  physical:
    type: do31
    address: 240
    digout: 17

#glocke
- topic: home/glocke
  physical:
    type: do31
    address: 240
    digout: 18
- topic: home/glocke/taster
  physical:
    type: sw8
    address: 30
    digin: 0

#var glocke enable
- topic: home/glocke/enable
  physical:
    type: var
    address: 240
    index: 1
    size: 1

#keller
- topic: home/ug/lager/licht
  physical:
    type: do31
    address: 240
    digout: 21
- topic: home/ug/stiege/licht
  physical:
    type: do31
    address: 240
    digout: 22
- topic: home/ug/arbeit/licht
  physical:
    type: do31
    address: 240
    digout: 23
- topic: home/ug/fitness/licht
  physical:
    type: do31
    address: 240
    digout: 24
- topic: home/ug/vorraum/licht
  physical:
    type: do31
    address: 240
    digout: 25
- topic: home/ug/technik/licht
  physical:
    type: do31
    address: 240
    digout: 26

#gang
- topic: home/eg/gang/licht
  physical:
    type: do31
    address: 241
    digout: 25

#arbeitszimmer
- topic: home/eg/arbeit/licht
  physical:
    type: do31
    address: 241
    digout: 26
- topic: home/eg/arbeit/rollo
  physical:
    type: do31
    address: 241
    shader: 11

#anna
- topic: home/og/anna/licht
  physical:
    type: do31
    address: 241
    digout: 27
- topic: home/og/anna/rollo
  physical:
    type: do31
    address: 241
    shader: 4

#severin
- topic: home/og/severin/licht
  physical:
    type: do31
    address: 241
    digout: 28
- topic: home/og/severin/ost/rollo
  physical:
    type: do31
    address: 241
    shader: 5
- topic: home/og/severin/nord/rollo
  physical:
    type: do31
    address: 241
    shader: 6

#wc og
- topic: home/og/wc/licht
  physical:
    type: do31
    address: 241
    digout: 29

#kueche
- topic: home/eg/kueche/licht
  physical:
    type: do31
    address: 240
    digout: 19
- topic: home/eg/kueche/wand/licht
  physical:
    type: do31
    address: 241
    digout: 30
- topic: home/eg/kueche/tuer/rollo
  physical:
    type: do31
    address: 241
    shader: 1
- topic: home/eg/kueche/fenster/rollo
  physical:
    type: do31
    address: 241
    shader: 9
- topic: home/eg/kueche/geschirrspueler/licht
  physical:
    type: pwm4
    address: 239
    pwmout: 0
- topic: home/eg/kueche/abwasch/licht
  physical:
    type: pwm4
    address: 239
    pwmout: 1
- topic: home/eg/kueche/kaffeemaschine/licht
  physical:
    type: pwm4
    address: 239
    pwmout: 2
- topic: home/eg/kueche/dunstabzug/licht
  physical:
    type: pwm4
    address: 239
    pwmout: 3

#speis
- topic: home/eg/speis/licht
  physical:
    type: do31
    address: 241
    digout: 24

#ess
- topic: home/eg/ess/licht
  physical:
    type: do31
    address: 240
    digout: 15
- topic: home/eg/ess/doppelfenster/rollo
  physical:
    type: do31
    address: 241
    shader: 0
- topic: home/eg/ess/fenster/rollo
  physical:
    type: do31
    address: 241
    shader: 3
- topic: home/eg/ess/tuer/rollo
  physical:
    type: do31
    address: 241
    shader: 10

#stiege og
- topic: home/og/stiege/netzteil
  physical:
    type: do31
    address: 240
    digout: 0
- topic: home/og/stiege/licht1
  physical:
    type: do31
    address: 240
    digout: 1
- topic: home/og/stiege/licht2
  physical:
    type: do31
    address: 240
    digout: 2
- topic: home/og/stiege/licht3
  physical:
    type: do31
    address: 240
    digout: 3
- topic: home/og/stiege/licht4
  physical:
    type: do31
    address: 240
    digout: 4
- topic: home/og/stiege/licht5
  physical:
    type: do31
    address: 240
    digout: 5
- topic: home/og/stiege/licht6
  physical:
    type: do31
    address: 240
    digout: 6

#garage
- topic: home/garage/licht
  physical:
    type: do31
    address: 240
    digout: 9
- topic: home/garage/tor/status
  physical:
    type: sw8
    address: 36
    digin: 0
#- topic: home/garage/tor/ausgang
#  physical:
#    type: sw8
#    address: 36
#    digout: 1
- topic: home/garage/tor/puls
  physical:
    type: sw8
    address: 36
    pulseout: 1

#terrasse
- topic: home/terrasse/licht
  physical:
    type: do31
    address: 240
    digout: 20
- topic: home/terrasse/markise
  physical:
    type: do31
    address: 241
    shader: 2

#eingang
- topic: home/eingang/licht
  physical:
    type: do31
    address: 240
    digout: 30
- topic: home/eingang/bewegungsmelder
  physical:
    type: sw8
    address: 101
    digin: 0
  receiver: [240]
#var licht eingang mode
- topic: home/eingang/licht/mode
  physical:
    type: var
    address: 240
    index: 2
    size: 1

#steckdose internet router
- topic: home/internet
  physical:
    type: do31
    address: 240
    digout: 27
    activelow: 1

#steckdose kameras
- topic: home/kamera
  physical:
    type: do31
    address: 240
    digout: 28
    activelow: 1
